# Generated by Django 5.1.6 on 2025-03-17 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='chatgroupmembership',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddIndex(
            model_name='chatgroup',
            index=models.Index(fields=['name'], name='chat_chatgr_name_96f303_idx'),
        ),
        migrations.AddIndex(
            model_name='chatgroupmembership',
            index=models.Index(fields=['group', 'user'], name='chat_chatgr_group_i_3e6e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp', 'group'], name='chat_messag_timesta_6854c4_idx'),
        ),
    ]
