# Generated by Django 5.1.6 on 2025-03-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
