# Generated by Django 5.1.6 on 2025-03-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_user_profile_picture_alter_user_cds_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_chat',
            field=models.BooleanField(default=True),
        ),
    ]
